import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get('window');

export const homeStyles = StyleSheet.create({
  container: {
      flex: 1,
      backgroundColor: '#fff',
    },
    header: {
      paddingTop: 40,
      paddingBottom: 60,
      paddingHorizontal: 30,
      alignItems: 'center',
      position: 'relative',
      overflow: 'hidden',
      backgroundColor: '#FFCC80',
      minHeight: height * 0.65,
    },
    decorativeShape: {
      position: 'absolute',
      borderRadius: 50,
      opacity: 0.7,
    },
    shape1: {
      width: 100,
      height: 100,
      backgroundColor: '#D9952D',
      top: '5%',
      left: -30,
    },
    shape2: {
      width: 80,
      height: 80,
      backgroundColor: '#F2980E',
      top: '15%',
      right: -20,
    },
    shape3: {
      width: 60,
      height: 60,
      backgroundColor: '#F57F17',
      top: '35%',
      left: 20,
    },
    shape4: {
      width: 70,
      height: 70,
      backgroundColor: '#FFA726',
      bottom: '25%',
      right: 10,
    },
    shape5: {
      width: 90,
      height: 90,
      backgroundColor: '#FF6F00',
      bottom: '10%',
      left: -25,
    },
    shape6: {
      width: 50,
      height: 50,
      backgroundColor: '#E64A19',
      top: '50%',
      right: -15,
    },
    headerContent: {
      alignItems: 'center',
      zIndex: 10,
      flex: 1,
      justifyContent: 'center',
    },
    appTitle: {
      fontSize: 36,
      fontWeight: 'bold',
      color: '#FF6B35',
      marginBottom: 30,
      textShadowColor: 'rgba(0, 0, 0, 0.1)',
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
    },
    imageContainer: {
      alignItems: 'center',
      marginBottom: 30,
    },
    imageCircle: {
      width: 200,
      height: 200,
      borderRadius: 100,
      backgroundColor: '#4DD0E1',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.3,
      shadowRadius: 15,
      elevation: 12,
    },
    mainImage: {
      width: 180,
      height: 180,
      borderRadius: 90,
    },
    appSubtitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#333',
      textAlign: 'center',
      marginBottom: 15,
      lineHeight: 26,
    },
    description: {
      fontSize: 14,
      color: '#4E342E',
      textAlign: 'center',
      paddingHorizontal: 20,
      lineHeight: 20,
    },
    mainContent: {
      backgroundColor: '#fff',
      paddingTop: 40,
    },
    featuresSection: {
      paddingHorizontal: 20,
      paddingVertical: 20,
    },
    featuresGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    featureCard: {
      width: '48%',
      backgroundColor: '#FFCCBC',
      padding: 15,
      borderRadius: 16,
      marginBottom: 16,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 4,
    },
    featureIcon: {
      width: 50,
      height: 50,
      borderRadius: 25,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 12,
    },
    featureImage: {
      width: 30,
      height: 30,
      borderRadius: 15,
    },
    featureTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: '#333',
      textAlign: 'center',
      marginBottom: 6,
    },
    featureDescription: {
      fontSize: 11,
      color: '#666',
      textAlign: 'center',
      lineHeight: 14,
    },
    ctaSection: {
      paddingHorizontal: 30,
      paddingVertical: 40,
      alignItems: 'center',
    },
    ctaButton: {
      width: '100%',
      marginBottom: 20,
      paddingVertical: 18,
      borderRadius: 50,
      alignItems: 'center',
      backgroundColor: '#FF6B35',
      shadowColor: '#FF6B35',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    ctaButtonText: {
      color: '#fff',
      fontSize: 18,
      fontWeight: 'bold',
    },
    registerButton: {
      paddingVertical: 12,
    },
    registerLink: {
      color: '#FF6B35',
      fontSize: 16,
      fontWeight: '600',
    },
  });