import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    paddingTop: 50,
    paddingBottom: 80,
    paddingHorizontal: 25,
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#FFA000',
    minHeight: height * 0.7,
  },
  decorativeShape: {
    position: 'absolute',
    borderRadius: 50,
    opacity: 0.8,
  },
  shape1: {
    width: 120,
    height: 120,
    backgroundColor: '#D9952D',
    top: '8%',
    left: -40,
  },
  shape2: {
    width: 90,
    height: 90,
    backgroundColor: '#FFCA28',
    top: '18%',
    right: -25,
  },
  shape3: {
    width: 70,
    height: 70,
    backgroundColor: '#F57F17',
    top: '40%',
    left: 15,
  },
  shape4: {
    width: 85,
    height: 85,
    backgroundColor: '#FFA726',
    bottom: '30%',
    right: 5,
  },
  shape5: {
    width: 110,
    height: 110,
    backgroundColor: '#FF6F00',
    bottom: '15%',
    left: -35,
  },
  shape6: {
    width: 60,
    height: 60,
    backgroundColor: '#E65100',
    top: '55%',
    right: -20,
  },
  shape7: {
    width: 50,
    height: 50,
    backgroundColor: '#FFEB3B',
    top: '25%',
    left: '60%',
  },
  shape8: {
    width: 65,
    height: 65,
    backgroundColor: '#E600CC',
    bottom: '45%',
    left: '15%',
  },
  headerContent: {
    alignItems: 'center',
    zIndex: 10,
    flex: 1,
    justifyContent: 'center',
    paddingTop: 20,
  },
  appTitle: {
    fontSize: 42,
    fontWeight: 'bold',
    color: '#FF6B35',
    marginBottom: 40,
    textShadow: '2px 2px 4px rgba(0,0,0,0.15)',
    letterSpacing: 1,
  },
  imageContainer: {
    alignItems: 'center',
    marginBottom: 35,
  },
  imageCircle: {
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: '#4DD0E1',
    justifyContent: 'center',
    alignItems: 'center',
    boxShadow: '0px 12px 20px rgba(0,0,0,0.4)',
    borderWidth: 6,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  mainImage: {
    width: 250,
    height: 250,
    borderRadius: 125,
  },
  appSubtitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#2D3748',
    textAlign: 'center',
    marginBottom: 18,
    lineHeight: 30,
    letterSpacing: 0.5,
  },
  description: {
    fontSize: 15,
    color: '#4A5568',
    textAlign: 'center',
    paddingHorizontal: 25,
    lineHeight: 22,
    fontWeight: '400',
  },
  mainContent: {
    backgroundColor: '#fff',
    paddingTop: 50,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    marginTop: -30,
    boxShadow: '0px -5px 10px rgba(0,0,0,0.1)',
  },
  featuresSection: {
    paddingHorizontal: 25,
    paddingVertical: 30,
  },
  sectionTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2D3748',
    textAlign: 'center',
    marginBottom: 35,
    letterSpacing: 0.5,
  },
  featuresGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  featureCard: {
    width: '48%',
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 20,
    marginBottom: 20,
    alignItems: 'center',
    boxShadow: '0px 4px 12px rgba(0,0,0,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.05)',
  },
  featureIcon: {
    width: 65,
    height: 65,
    borderRadius: 32.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
    boxShadow: '0px 2px 4px rgba(0,0,0,0.1)',
  },
  featureImage: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
  },
  featureTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2D3748',
    textAlign: 'center',
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  featureDescription: {
    fontSize: 12,
    color: '#718096',
    textAlign: 'center',
    lineHeight: 16,
    fontWeight: '400',
  },
  testimonialSection: {
    paddingHorizontal: 25,
    paddingVertical: 50,
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    borderRadius: 30,
    marginBottom: 40,
    boxShadow: '0px 10px 25px rgba(255,138,101,0.2)',
    borderWidth: 2,
    borderColor: 'rgba(255, 138, 101, 0.1)',
  },
  testimonialCard: {
    backgroundColor: 'transparent',
    padding: 25,
    borderRadius: 25,
    alignItems: 'center',
  },
  testimonialAvatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    marginBottom: 25,
    borderWidth: 4,
    borderColor: '#FF8A65',
    boxShadow: '0px 5px 10px rgba(255,138,101,0.3)',
  },
  testimonialText: {
    fontSize: 17,
    color: '#4A5568',
    textAlign: 'center',
    fontStyle: 'italic',
    marginBottom: 15,
    lineHeight: 26,
    fontWeight: '500',
  },
  testimonialAuthor: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FF8A65',
    letterSpacing: 0.5,
  },
  ctaSection: {
    paddingHorizontal: 30,
    paddingVertical: 60,
    alignItems: 'center',
    backgroundColor: '#E0E0E0',
    marginHorizontal: 15,
    borderRadius: 35,
    marginBottom: 30,
    boxShadow: '0px 15px 30px rgba(0,0,0,0.1)',
  },
  ctaTitle: {
    fontSize: 30,
    fontWeight: '900',
    color: '#2D3748',
    textAlign: 'center',
    marginBottom: 40,
    lineHeight: 38,
    letterSpacing: 0.8,
  },
  ctaButton: {
    width: '80%',
    marginBottom: 30,
    paddingVertical: 22,
    borderRadius: 60,
    alignItems: 'center',
    backgroundColor: '#FF5722',
    boxShadow: '0px 8px 20px rgba(255,87,34,0.4)',
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  ctaButtonText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 1,
    textShadow: '1px 1px 3px rgba(0,0,0,0.2)',
  },
  registerButton: {
    paddingVertical: 18,
    paddingHorizontal: 25,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: '#FF8A65',
  },
  registerLink: {
    color: '#FF8A65',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  heroSection: {
    paddingHorizontal: 25,
    paddingVertical: 40,
    alignItems: 'center',
  },
  heroImage: {
    width: width * 0.85,
    height: 250,
    borderRadius: 20,
    marginBottom: 25,
  },
  heroContent: {
    alignItems: 'center',
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2D3748',
    textAlign: 'center',
    marginBottom: 15,
    lineHeight: 34,
  },
  heroDescription: {
    fontSize: 16,
    color: '#4A5568',
    textAlign: 'center',
    lineHeight: 24,
    paddingHorizontal: 20,
  },
  logoImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
});
